project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: "Home"
  sidebar:
    style: "docked"
    pinned: false
    contents: auto
  page-navigation: true
  back-to-top-navigation: true

theme: 
  light: flatly
  dark: darkly

engine: knitr

toc: true
number-sections: true

fig-dpi: 300
bibliography: bibliography.bib
citeproc: true
link-citations: true

code-fold: true
code-overflow: wrap


format:
  html:
    useMath: true

execute:
  freeze: true
  cache: true
